export const SET_APP_CONFIGURATION = "SET_APP_CONFIGURATION";
export const SET_EMPLOYEE = "SET_EMPLOYEE";
export const SET_VAN = "SET_VAN";
export const SET_WAREHOUSE = "SET_WAREHOUSE";
export const IN_PROGRESS = "IN_PROGRESS";
export const MESSAGE_FLAG="MESSAGE_DATA";
